// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZaU_3zyrVpCdcvDCOcKF4mY5OqHbgRMI',
    appId: '1:563485116497:web:23a026091026b36c969070',
    messagingSenderId: '563485116497',
    projectId: 'auto-ecole-4cea4',
    authDomain: 'auto-ecole-4cea4.firebaseapp.com',
    storageBucket: 'auto-ecole-4cea4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD3TDCOlXnF3w4pbIx4wzcOPZD0OGhYys',
    appId: '1:563485116497:android:0b736ec45a8baa3a969070',
    messagingSenderId: '563485116497',
    projectId: 'auto-ecole-4cea4',
    storageBucket: 'auto-ecole-4cea4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGimlY97Q5F3HwK2F2uLNscsdU9kZcsDs',
    appId: '1:563485116497:ios:c1b0724f9a46526f969070',
    messagingSenderId: '563485116497',
    projectId: 'auto-ecole-4cea4',
    storageBucket: 'auto-ecole-4cea4.appspot.com',
    iosBundleId: 'com.example.autoEcole',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGimlY97Q5F3HwK2F2uLNscsdU9kZcsDs',
    appId: '1:563485116497:ios:c1b0724f9a46526f969070',
    messagingSenderId: '563485116497',
    projectId: 'auto-ecole-4cea4',
    storageBucket: 'auto-ecole-4cea4.appspot.com',
    iosBundleId: 'com.example.autoEcole',
  );
}
